# Generated by Django 4.2.13 on 2024-06-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("novel_food", "0001_initial"),
        ("taxonomies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ADME",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_pktkade", primary_key=True, serialize=False
                    ),
                ),
                (
                    "test_material",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        db_column="study_comment",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "guideline",
                    models.ForeignKey(
                        blank=True,
                        help_text="(GUIDELINE vocab)",
                        limit_choices_to={"taxonomy__code": "GUIDELINE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guideline_admes",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "guideline_qualifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guideline_qualifier_admes",
                        to="taxonomies.guidelinequalifier",
                    ),
                ),
                (
                    "novel_food",
                    models.ForeignKey(
                        db_column="pktkade_study",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="novel_food.novelfood",
                    ),
                ),
            ],
            options={
                "verbose_name": "ADME Study",
                "verbose_name_plural": "ADME Studies 🎸🔬",
                "db_table": "PKTK",
            },
        ),
        migrations.CreateModel(
            name="AssessmentRemarks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_assess", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="assess", max_length=255)),
                ("definition", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Assessment Remarks",
                "verbose_name_plural": "Assessment Remarks",
                "db_table": "ASSESSMENT",
            },
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lovalue", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Endpoint",
                "verbose_name_plural": "📂 Endpoints",
                "db_table": "ENDPOINT",
            },
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_hazard", primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.FloatField(blank=True, db_column="risk_value", null=True),
                ),
                (
                    "uncertainty_factor",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="uncertainty factor"
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "assessment_remarks",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_assess",
                        help_text="This field provides additional information regarding "
                        "the assessment particularly when no health-based "
                        "guidance value (e.g., ADI, TDI) is provided in the Opinion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studies.assessmentremarks",
                        verbose_name="Assessment Remarks",
                    ),
                ),
                (
                    "assessment_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_assessment_type",
                        help_text="(ENDPOINT_HGV vocab)",
                        limit_choices_to={"taxonomy__code": "ENDPOINT_HGV"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_type_outcomes",
                        to="taxonomies.taxonomynode",
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_endpoint",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studies.endpoint",
                    ),
                ),
                (
                    "risk_qualifier",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_risk_qualifier",
                        help_text="(QUALIFIER vocab)",
                        limit_choices_to={"taxonomy__code": "QUALIFIER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_qualifier_outcomes",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_risk_unit",
                        help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                        limit_choices_to={"taxonomy__code": "UNIT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit_outcomes",
                        to="taxonomies.taxonomynode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Final Outcome",
                "verbose_name_plural": "Final Outcomes 🎰",
                "db_table": "HAZARD",
            },
        ),
        migrations.CreateModel(
            name="StudySource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_study_type", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Study Sources",
                "db_table": "STUDY_SOURCE",
            },
        ),
        migrations.CreateModel(
            name="StudyType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_study_type", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "ADME Study Type",
                "verbose_name_plural": "ADME Study Types",
                "db_table": "STUDY_TYPE",
            },
        ),
        migrations.CreateModel(
            name="OutcomePopulation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_hazard_age", primary_key=True, serialize=False
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        db_column="id_hazard",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studies.outcome",
                    ),
                ),
                (
                    "population",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_age",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="population_outcome_populations",
                        to="taxonomies.population",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outcome Population",
                "verbose_name_plural": "Outcome Populations",
                "db_table": "HAZARD_AGE",
            },
        ),
        migrations.CreateModel(
            name="Genotox",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_tox", primary_key=True, serialize=False
                    ),
                ),
                (
                    "test_material",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "genotox_guideline",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_genotox_guideline",
                        help_text="(GUIDELINE vocab)",
                        limit_choices_to={"taxonomy__code": "GUIDELINE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="genotox_guideline_genotoxes",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "guideline_qualifier",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_guideline_qualifier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guideline_qualifier_genotoxes",
                        to="taxonomies.guidelinequalifier",
                    ),
                ),
                (
                    "novel_food",
                    models.ForeignKey(
                        db_column="id_study",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="novel_food.novelfood",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_is_genotoxic",
                        help_text="(POSNEG vocab)",
                        limit_choices_to={"taxonomy__code": "POSNEG"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outcome_genotoxes",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "study_source",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_study_source",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_source_genotoxes",
                        to="studies.studysource",
                    ),
                ),
                (
                    "test_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_test_type",
                        help_text="for ex.: acute oral toxicity (OECD phrase ID 1703), or "
                        "subchronic (OECD phrase ID 2399). (TEST_TYPE vocab)",
                        limit_choices_to={"taxonomy__code": "TEST_TYPE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_type_genotoxes",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "testing_method",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_testing_method",
                        help_text="for ex.: in silico, in vitro, in vivo, human study etc. "
                        "(TEST_TYPE vocab)",
                        limit_choices_to={"taxonomy__code": "TEST_TYPE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testing_method_genotoxes",
                        to="taxonomies.taxonomynode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genotox Study",
                "verbose_name_plural": "Genotox Studies 🧬🔬",
                "db_table": "GENOTOX",
            },
        ),
        migrations.CreateModel(
            name="Endpointstudy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_tox", primary_key=True, serialize=False
                    ),
                ),
                ("exp_duration", models.FloatField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "test_material",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "duration_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_duration_unit",
                        help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                        limit_choices_to={"taxonomy__code": "UNIT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duration_unit_endpointstudies",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "guideline",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_guideline",
                        help_text="(GUIDELINE vocab)",
                        limit_choices_to={"taxonomy__code": "GUIDELINE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guideline_endpointstudies",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "guideline_qualifier",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_guideline_qualifier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guideline_qualifier_endpointstudies",
                        to="taxonomies.guidelinequalifier",
                    ),
                ),
                (
                    "novel_food",
                    models.ForeignKey(
                        db_column="id_study",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="novel_food.novelfood",
                    ),
                ),
                (
                    "sex",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_sex",
                        help_text="(MTX vocab)",
                        limit_choices_to={"taxonomy__code": "MTX"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sex_endpointstudies",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_species",
                        help_text="(MTX vocab)",
                        limit_choices_to={"taxonomy__code": "MTX"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="species_endpointstudies",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "study_source",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_study_source",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_source_endpointstudies",
                        to="studies.studysource",
                    ),
                ),
                (
                    "test_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_test_type",
                        help_text="for ex.: acute oral toxicity (OECD phrase ID 1703), or "
                        "subchronic (OECD phrase ID 2399) (TEST_TYPE vocab)",
                        limit_choices_to={"taxonomy__code": "TEST_TYPE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_type_endpointstudies",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "testing_method",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_testing_method",
                        help_text="for ex.: in silico, in vitro, in vivo, "
                        "human study etc. (TEST_TYPE vocab)",
                        limit_choices_to={"taxonomy__code": "TEST_TYPE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testing_method_endpointstudies",
                        to="taxonomies.taxonomynode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endpoint Study",
                "verbose_name_plural": "Endpoint Studies 📐🔬",
                "db_table": "ENDPOINTSTUDY",
            },
        ),
        migrations.AddField(
            model_name="endpoint",
            name="endpointstudy",
            field=models.ForeignKey(
                db_column="id_tox",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpointstudy_end_endstudy_outcomes",
                to="studies.endpointstudy",
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="qualifier",
            field=models.ForeignKey(
                blank=True,
                db_column="id_qualifier",
                help_text="(QUALIFIER vocab)",
                limit_choices_to={"taxonomy__code": "QUALIFIER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qualifier_end_endstudy_outcomes",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="reference_point",
            field=models.ForeignKey(
                blank=True,
                db_column="id_endpoint",
                help_text="(ENDPOINT_HGV vocab)",
                limit_choices_to={"taxonomy__code": "ENDPOINT_HGV"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="endpoint_end_endstudy_outcomes",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="sex",
            field=models.ForeignKey(
                blank=True,
                db_column="id_sex",
                help_text="(MTX vocab)",
                limit_choices_to={"taxonomy__code": "MTX"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sex_end_endstudy_outcomes",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="id_unit",
                help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                limit_choices_to={"taxonomy__code": "UNIT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_end_endstudy_outcomes",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.CreateModel(
            name="ADMEStudyType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_pktkade_study_type",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adme",
                    models.ForeignKey(
                        db_column="id_pktkade",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studies.adme",
                    ),
                ),
                (
                    "study_type",
                    models.ForeignKey(
                        db_column="id_study_type",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studies.studytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "ADME Study Type",
                "verbose_name_plural": "ADME Study Types",
                "db_table": "PKTK_STUDY_TYPE",
            },
        ),
        migrations.AddField(
            model_name="adme",
            name="study_source",
            field=models.ForeignKey(
                blank=True,
                db_column="id_study_source",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_source_admes",
                to="studies.studysource",
            ),
        ),
        migrations.AddField(
            model_name="adme",
            name="testing_method",
            field=models.ForeignKey(
                blank=True,
                db_column="assay_system_endpoint",
                help_text="for ex.: in silico, in vitro, in vivo, human study etc. "
                "(TEST_TYPE vocab)",
                limit_choices_to={"taxonomy__code": "TEST_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testing_method_admes",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AddConstraint(
            model_name="outcomepopulation",
            constraint=models.UniqueConstraint(
                fields=("outcome", "population"), name="unique_outcome_population"
            ),
        ),
    ]
