# Generated by Django 4.2.13 on 2024-06-03 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adme",
            options={"verbose_name": "ADME", "verbose_name_plural": "ADMEs"},
        ),
    ]
