# Generated by Django 4.2.13 on 2024-06-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ADMEInvestigationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_pktkade_investigation_type",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adme",
                    models.ForeignKey(
                        db_column="id_pktkade",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studies.adme",
                    ),
                ),
            ],
            options={
                "verbose_name": "ADME Study Type",
                "verbose_name_plural": "ADME Study Types",
                "db_table": "PKTK_INVESTIGATION_TYPE",
            },
        ),
        migrations.CreateModel(
            name="InvestigationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_investigation_type",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "ADME Study Type",
                "verbose_name_plural": "ADME Study Types",
                "db_table": "INVESTIGATION_TYPE",
            },
        ),
        migrations.AlterField(
            model_name="studysource",
            name="id",
            field=models.AutoField(
                db_column="id_study_source", primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="ADMEStudyType",
        ),
        migrations.DeleteModel(
            name="StudyType",
        ),
        migrations.AddField(
            model_name="admeinvestigationtype",
            name="investigation_type",
            field=models.ForeignKey(
                db_column="id_investigation_type",
                on_delete=django.db.models.deletion.CASCADE,
                to="studies.investigationtype",
            ),
        ),
    ]
