# Generated by Django 4.2.13 on 2024-06-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0001_initial"),
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finaloutcome",
            name="assessment_remarks",
        ),
        migrations.RemoveField(
            model_name="finaloutcome",
            name="risk_qualifier",
        ),
        migrations.AddField(
            model_name="finaloutcome",
            name="qualifier",
            field=models.ForeignKey(
                blank=True,
                db_column="id_risk_qualifier",
                help_text="(QUALIFIER vocab)",
                limit_choices_to={"taxonomy__code": "QUALIFIER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qualifier_final_outcomes",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="finaloutcome",
            name="outcome",
            field=models.ForeignKey(
                blank=True,
                db_column="id_assessment_type",
                help_text="(ENDPOINT_HGV vocab)",
                limit_choices_to={"taxonomy__code": "ENDPOINT_HGV"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outcome_final_outcomes",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="finaloutcome",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="id_risk_unit",
                help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                limit_choices_to={"taxonomy__code": "UNIT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_final_outcomes",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.DeleteModel(
            name="AssessmentRemarks",
        ),
    ]
