# Generated by Django 4.2.13 on 2024-06-03 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0002_alter_adme_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admestudytype",
            options={
                "verbose_name": "ADME Study Type",
                "verbose_name_plural": "ADME Study Types",
            },
        ),
        migrations.AlterModelOptions(
            name="endendstudyoutcome",
            options={
                "verbose_name": "Endpoint Endpointstudy Outcome",
                "verbose_name_plural": "Endpoint Endpointstudy Outcomes",
            },
        ),
        migrations.AlterModelOptions(
            name="endpointstudy",
            options={
                "verbose_name": "Endpointstudy",
                "verbose_name_plural": "Endpointstudies",
            },
        ),
        migrations.AlterModelOptions(
            name="genotox",
            options={"verbose_name": "Genotox", "verbose_name_plural": "Genotoxes"},
        ),
        migrations.AlterModelTable(
            name="endendstudyoutcome",
            table="END_ENDSTUDY_HAZARD",
        ),
        migrations.AlterModelTable(
            name="endpointstudy",
            table="ENDPOINTSTUDY",
        ),
        migrations.AlterModelTable(
            name="genotox",
            table="GENOTOX",
        ),
    ]
