# Generated by Django 4.2.13 on 2024-06-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0002_alter_endpoint_reference_point_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="id",
            field=models.AutoField(
                db_column="id_endpoint", primary_key=True, serialize=False
            ),
        ),
    ]
