# Generated by Django 4.2.13 on 2024-06-21 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0002_admeinvestigationtype_investigationtype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admeinvestigationtype",
            options={
                "verbose_name": "ADME Investigation Type",
                "verbose_name_plural": "ADME Investigation Types",
            },
        ),
        migrations.AlterModelOptions(
            name="investigationtype",
            options={
                "verbose_name": "ADME Investigation Type",
                "verbose_name_plural": "ADME Investigation Types",
            },
        ),
    ]
