# Generated by Django 4.2.13 on 2024-06-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0003_alter_admestudytype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adme",
            name="remarks",
            field=models.TextField(
                blank=True, db_column="study_comment", max_length=2000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="adme",
            name="test_material",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
