# Generated by Django 4.2.13 on 2024-06-28 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0003_alter_endpoint_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finaloutcome",
            old_name="uncertainty_factor",
            new_name="uncertainity_factor",
        ),
    ]
