# Generated by Django 4.2.13 on 2024-06-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0001_initial"),
        ("studies", "0004_alter_adme_remarks_alter_adme_test_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificToxicityStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_spec_tox",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"taxonomy__code": "TOXICITY"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="id_spec_tox_specific_toxicity_studies",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "id_tox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studies.endpointstudy",
                    ),
                ),
            ],
        ),
    ]
