# Generated by Django 4.2.13 on 2024-06-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0004_rename_uncertainty_factor_finaloutcome_uncertainity_factor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="lovalue",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="endpointstudy",
            name="study_duration",
            field=models.DecimalField(
                blank=True,
                db_column="exp_duration",
                decimal_places=4,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="finaloutcome",
            name="value",
            field=models.DecimalField(
                blank=True,
                db_column="risk_value",
                decimal_places=4,
                max_digits=10,
                null=True,
            ),
        ),
    ]
