# Generated by Django 4.2.13 on 2024-06-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0001_initial"),
        ("studies", "0004_remove_genotox_genotox_guideline_genotox_guideline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adme",
            name="testing_method",
        ),
        migrations.RemoveField(
            model_name="endpointstudy",
            name="testing_method",
        ),
        migrations.RemoveField(
            model_name="genotox",
            name="testing_method",
        ),
        migrations.AddField(
            model_name="adme",
            name="test_type",
            field=models.ForeignKey(
                blank=True,
                db_column="assay_system_endpoint",
                help_text="for ex.: in silico, in vitro, in vivo, human "
                "study etc. (TEST_TYPE vocab)",
                limit_choices_to={"taxonomy__code": "TEST_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_type_admes",
                to="taxonomies.taxonomynode",
            ),
        ),
    ]
