# Generated by Django 4.2.13 on 2024-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0005_alter_endpoint_lovalue_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genotox",
            options={
                "verbose_name": "Genotoxicity Study 🔬🧬",
                "verbose_name_plural": "Genotoxicity Studies 🔬🧬",
            },
        ),
        migrations.RenameField(
            model_name="finaloutcome",
            old_name="uncertainity_factor",
            new_name="uncertainty_factor",
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="lovalue",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Value",
            ),
        ),
    ]
