# Generated by Django 4.2.13 on 2024-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0005_specifictoxicitystudy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endendstudyoutcome",
            name="lovalue",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="endpointstudy",
            name="exp_duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="endpointstudy",
            name="remarks",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="endpointstudy",
            name="test_material",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
