# Generated by Django 4.2.13 on 2024-07-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0006_alter_genotox_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admeinvestigationtype",
            name="adme",
            field=models.ForeignKey(
                db_column="id_pktkade",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investigation_types",
                to="studies.adme",
            ),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="endpointstudy",
            field=models.ForeignKey(
                db_column="id_tox",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpoints",
                to="studies.endpointstudy",
            ),
        ),
        migrations.AlterField(
            model_name="finaloutcomepopulation",
            name="final_outcome",
            field=models.ForeignKey(
                db_column="id_hazard",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="populations",
                to="studies.finaloutcome",
            ),
        ),
    ]
