# Generated by Django 4.2.13 on 2024-06-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0006_alter_endendstudyoutcome_lovalue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genotox",
            old_name="genotox_genotox_guideline",
            new_name="genotox_guideline",
        ),
        migrations.AlterField(
            model_name="genotox",
            name="test_material",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
