# Generated by Django 4.2.13 on 2024-07-27 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0007_alter_admeinvestigationtype_adme_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investigationtype",
            options={
                "verbose_name": "Investigation Type",
                "verbose_name_plural": "Investigation Types",
            },
        ),
    ]
