# Generated by Django 4.2.14 on 2024-08-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taxonomies",
            "0006_taxonomynode_is_gender_taxonomynode_is_part_nature_and_more",
        ),
        ("studies", "0010_alter_endpointstudy_test_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpointstudy",
            name="species",
            field=models.ForeignKey(
                blank=True,
                db_column="id_species",
                help_text="(MTX vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "MTX"),
                    models.Q(
                        ("extended_name__icontains", "(as animal)"),
                        ("extended_name__icontains", "(as organism)"),
                        ("short_name__icontains", "(as animal)"),
                        ("short_name__icontains", "(as organism)"),
                        _connector="OR",
                    ),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_endpointstudies",
                to="taxonomies.taxonomynode",
            ),
        ),
    ]
