# Generated by Django 4.2.13 on 2024-06-05 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("novel_food", "0001_initial"),
        ("taxonomies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodForm",
            fields=[
                ("id_food_form", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the food form", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Form",
                "verbose_name_plural": "Food Forms - options",
                "db_table": "FOOD_FORM",
            },
        ),
        migrations.CreateModel(
            name="NovelFoodVariant",
            fields=[
                (
                    "id_novel_food_variant",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "novel_food",
                    models.ForeignKey(
                        db_column="study_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="novel_food.novelfood",
                    ),
                ),
            ],
            options={
                "verbose_name": "Novel Food Variant",
                "verbose_name_plural": " Novel Food Variants",
                "db_table": "NOVEL_FOOD_VARIANT",
            },
        ),
        migrations.CreateModel(
            name="ParameterType",
            fields=[
                (
                    "id_parameter_type",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Parameter type", max_length=255, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Parameter Type",
                "verbose_name_plural": "Parameter Types - options",
                "db_table": "PARAMETER_TYPE",
            },
        ),
        migrations.CreateModel(
            name="ProposedUseType",
            fields=[
                ("id_use_type", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("whole_foods", "Whole foods"),
                            ("food_ingredients", "Food ingredients"),
                            ("food_supplements", "Food supplements"),
                            (
                                "infant_follow_on_formula",
                                "Infant formula and follow-on formula",
                            ),
                            (
                                "special_medical_purpose",
                                "Food for special medical purposes",
                            ),
                            (
                                "total_diet_replacement",
                                "Total diet replacement for weight control",
                            ),
                        ],
                        help_text="Title of the proposed use type",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposed Use Type",
                "verbose_name_plural": "Proposed Use Types - options",
                "db_table": "PROPOSED_USE_TYPE",
            },
        ),
        migrations.CreateModel(
            name="RiskAssessmentRedFlags",
            fields=[
                (
                    "id_risk_assessment_red_flags",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the risk assessment red flags",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskAssessmentRedFlagsNFVariant",
            fields=[
                (
                    "id_risk_assessment_red_flags_novel_food",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "nf_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composition.novelfoodvariant",
                    ),
                ),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composition.riskassessmentredflags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk assessment red flag",
                "verbose_name_plural": "Risk assessment red flags",
            },
        ),
        migrations.CreateModel(
            name="ProposedUse",
            fields=[
                (
                    "id_proposed_use",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "nf_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composition.novelfoodvariant",
                    ),
                ),
                (
                    "population",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_age",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="population_proposed_uses",
                        to="taxonomies.population",
                    ),
                ),
                (
                    "use_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="composition.proposedusetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionNovelFoodVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_novel_food_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composition.novelfoodvariant",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"taxonomy__code": "MTX"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_production_novel_food_variants",
                        to="taxonomies.taxonomynode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Process",
                "verbose_name_plural": "Production Process",
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                ("id_parameter", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Parameter", max_length=255, unique=True
                    ),
                ),
                (
                    "param_tax_node",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_param_tax_node",
                        limit_choices_to={"taxonomy__code": "PARAM"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="param_tax_node_parameters",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="composition.parametertype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parameter",
                "verbose_name_plural": "Parameters - options",
                "db_table": "PARAMETER",
            },
        ),
        migrations.AddField(
            model_name="novelfoodvariant",
            name="risk_assessment_red_flags",
            field=models.ManyToManyField(
                through="composition.RiskAssessmentRedFlagsNFVariant",
                to="composition.riskassessmentredflags",
            ),
        ),
        migrations.CreateModel(
            name="FoodFormNovelFoodVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composition.foodform",
                    ),
                ),
                (
                    "novel_food_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composition.novelfoodvariant",
                    ),
                ),
            ],
            options={
                "db_table": "FOOD_FORM_NF_VARIANT",
            },
        ),
        migrations.CreateModel(
            name="Composition",
            fields=[
                ("id_composition", models.AutoField(primary_key=True, serialize=False)),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Value of the parameter",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "upper_range_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Optional upper range value of the parameter",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("specification", "Specification"),
                            ("characterisation", "Characterisation"),
                            ("other", "Other"),
                        ],
                        help_text="Specification/Composition/Other",
                        max_length=255,
                    ),
                ),
                ("footnote", models.CharField(blank=True, max_length=2000)),
                (
                    "novel_food_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="composition.novelfoodvariant",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="composition.parameter",
                    ),
                ),
                (
                    "qualifier",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_qualifier",
                        limit_choices_to={"taxonomy__code": "QUALIFIER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qualifier_compositions",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_unit",
                        limit_choices_to={"taxonomy__code": "UNIT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit_compositions",
                        to="taxonomies.taxonomynode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackgroundExposureAssessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_bg_exp_assessment",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comp_of_interest",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_comp_of_interest",
                        help_text="Compound of interest",
                        limit_choices_to={"taxonomy__code": "PARAM"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comp_of_interest_bg_expo_assessments",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "novel_food",
                    models.ForeignKey(
                        db_column="id_study",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novel_food_bg_expo_assessments",
                        to="novel_food.novelfood",
                    ),
                ),
            ],
        ),
    ]
