# Generated by Django 4.2.13 on 2024-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="title",
            field=models.CharField(help_text="Parameter", max_length=255, unique=True),
        ),
    ]
