# Generated by Django 4.2.13 on 2024-06-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="riskassessmentredflagsnfvariant",
            old_name="risk_assessment",
            new_name="risk_assessment_red_flags",
        ),
        migrations.AlterField(
            model_name="proposeduse",
            name="use_type",
            field=models.CharField(
                choices=[
                    ("whole foods", "Whole foods"),
                    ("food ingredients", "Food ingredients"),
                    ("food supplements", "Food supplements"),
                    (
                        "infant follow on formula",
                        "Infant formula and follow-on formula",
                    ),
                    ("special medical purpose", "Food for special medical purposes"),
                    (
                        "total diet replacement",
                        "Total diet replacement for weight control",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
