# Generated by Django 4.2.13 on 2024-06-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0001_initial"),
        ("composition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="qualifier",
            field=models.ForeignKey(
                blank=True,
                db_column="id_qualifier",
                help_text="(QUALIFIER vocab)",
                limit_choices_to={"taxonomy__code": "QUALIFIER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qualifier_compositions",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="composition",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="id_unit",
                help_text="(UNIT vocab)",
                limit_choices_to={"taxonomy__code": "UNIT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_compositions",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="param_tax_node",
            field=models.ForeignKey(
                blank=True,
                db_column="id_param_tax_node",
                help_text="(PARAM vocab)",
                limit_choices_to={"taxonomy__code": "PARAM"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="param_tax_node_parameters",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="productionnovelfoodvariant",
            name="process",
            field=models.ForeignKey(
                blank=True,
                help_text="(MTX vocab)",
                limit_choices_to={"taxonomy__code": "MTX"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="process_production_novel_food_variants",
                to="taxonomies.taxonomynode",
            ),
        ),
    ]
