# Generated by Django 4.2.13 on 2024-07-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0005_alter_population_subgroup_and_more"),
        ("composition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="composition",
            options={
                "verbose_name": "Composition",
                "verbose_name_plural": "Composition",
            },
        ),
        migrations.AlterModelOptions(
            name="productionnovelfoodvariant",
            options={
                "verbose_name": "Production Process",
                "verbose_name_plural": "Production Process",
            },
        ),
        migrations.AlterModelOptions(
            name="proposeduse",
            options={
                "verbose_name": "Proposed Use",
                "verbose_name_plural": "Proposed Use",
            },
        ),
        migrations.AlterField(
            model_name="productionnovelfoodvariant",
            name="process",
            field=models.ForeignKey(
                blank=True,
                db_column="id_process",
                help_text="(MTX vocab)",
                limit_choices_to={"taxonomy__code": "MTX"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="process_production_novel_food_variants",
                to="taxonomies.taxonomynode",
                verbose_name="Process Step",
            ),
        ),
        migrations.AlterField(
            model_name="proposeduse",
            name="population",
            field=models.ForeignKey(
                blank=True,
                db_column="id_age",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="population_proposed_uses",
                to="taxonomies.population",
                verbose_name="Target Population",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessredflagnfvariant",
            name="risk_assess_red_flag",
            field=models.ForeignKey(
                db_column="id_risk_assess_red_flag",
                on_delete=django.db.models.deletion.CASCADE,
                to="composition.riskassessredflag",
                verbose_name="Red Flag",
            ),
        ),
    ]
