# Generated by Django 4.2.13 on 2024-06-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "composition",
            "0002_rename_risk_assessment_riskassessmentredflagsnfvariant_risk_"
            "assessment_red_flags_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessRedFlags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_risk_assess_red_flags",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the risk assessment red flags",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk assessment red flag",
                "verbose_name_plural": "Risk assessment red flags",
                "db_table": "RISK_ASSESS_RED_FLAGS",
            },
        ),
        migrations.CreateModel(
            name="RiskAssessRedFlagsNFVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_risk_assess_red_flags_nf_variant",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk assessment red flag",
                "verbose_name_plural": "Risk assessment red flags",
                "db_table": "RISK_ASSESS_RED_FLAGS_NF_VARIANT",
            },
        ),
        migrations.RemoveField(
            model_name="riskassessmentredflagsnfvariant",
            name="nf_variant",
        ),
        migrations.RemoveField(
            model_name="riskassessmentredflagsnfvariant",
            name="risk_assessment_red_flags",
        ),
        migrations.RemoveField(
            model_name="novelfoodvariant",
            name="risk_assessment_red_flags",
        ),
        migrations.DeleteModel(
            name="RiskAssessmentRedFlags",
        ),
        migrations.DeleteModel(
            name="RiskAssessmentRedFlagsNFVariant",
        ),
        migrations.AddField(
            model_name="riskassessredflagsnfvariant",
            name="nf_variant",
            field=models.ForeignKey(
                db_column="id_nf_variant",
                on_delete=django.db.models.deletion.CASCADE,
                to="composition.novelfoodvariant",
            ),
        ),
        migrations.AddField(
            model_name="riskassessredflagsnfvariant",
            name="risk_assess_red_flags",
            field=models.ForeignKey(
                db_column="id_risk_assess_red_flags",
                on_delete=django.db.models.deletion.CASCADE,
                to="composition.riskassessredflags",
            ),
        ),
        migrations.AddField(
            model_name="novelfoodvariant",
            name="risk_assess_red_flags",
            field=models.ManyToManyField(
                through="composition.RiskAssessRedFlagsNFVariant",
                to="composition.riskassessredflags",
            ),
        ),
    ]
