# Generated by Django 4.2.13 on 2024-07-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0003_proposeduse_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="nf_variant",
            field=models.ForeignKey(
                db_column="id_nf_variant",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compositions",
                to="composition.novelfoodvariant",
            ),
        ),
        migrations.AlterField(
            model_name="productionnovelfoodvariant",
            name="nf_variant",
            field=models.ForeignKey(
                db_column="id_nf_variant",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productions",
                to="composition.novelfoodvariant",
            ),
        ),
        migrations.AlterField(
            model_name="proposeduse",
            name="nf_variant",
            field=models.ForeignKey(
                db_column="id_nf_variant",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposed_uses",
                to="composition.novelfoodvariant",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessredflagnfvariant",
            name="nf_variant",
            field=models.ForeignKey(
                db_column="id_nf_variant",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_assess_red_flags",
                to="composition.novelfoodvariant",
            ),
        ),
    ]
