# Generated by Django 4.2.13 on 2024-06-25 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0003_riskassessredflags_riskassessredflagsnfvariant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessRedFlag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_risk_assess_red_flag",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the risk assessment red flags",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk assessment red flag",
                "verbose_name_plural": "Risk assessment red flags",
                "db_table": "RISK_ASSESS_RED_FLAG",
            },
        ),
        migrations.CreateModel(
            name="RiskAssessRedFlagNFVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_risk_assess_red_flag_nf_variant",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk assessment red flag",
                "verbose_name_plural": "Risk assessment red flags",
                "db_table": "RISK_ASSESS_RED_FLAG_NF_VARIANT",
            },
        ),
        migrations.RemoveField(
            model_name="riskassessredflagsnfvariant",
            name="nf_variant",
        ),
        migrations.RemoveField(
            model_name="riskassessredflagsnfvariant",
            name="risk_assess_red_flags",
        ),
        migrations.RemoveField(
            model_name="novelfoodvariant",
            name="risk_assess_red_flags",
        ),
        migrations.DeleteModel(
            name="RiskAssessRedFlags",
        ),
        migrations.DeleteModel(
            name="RiskAssessRedFlagsNFVariant",
        ),
        migrations.AddField(
            model_name="riskassessredflagnfvariant",
            name="nf_variant",
            field=models.ForeignKey(
                db_column="id_nf_variant",
                on_delete=django.db.models.deletion.CASCADE,
                to="composition.novelfoodvariant",
            ),
        ),
        migrations.AddField(
            model_name="riskassessredflagnfvariant",
            name="risk_assess_red_flag",
            field=models.ForeignKey(
                db_column="id_risk_assess_red_flag",
                on_delete=django.db.models.deletion.CASCADE,
                to="composition.riskassessredflag",
            ),
        ),
        migrations.AddField(
            model_name="novelfoodvariant",
            name="risk_assess_red_flag",
            field=models.ManyToManyField(
                through="composition.RiskAssessRedFlagNFVariant",
                to="composition.riskassessredflag",
            ),
        ),
    ]
