# Generated by Django 4.2.13 on 2024-07-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0004_alter_composition_nf_variant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="title",
            field=models.CharField(help_text="Parameter", max_length=255, unique=True),
        ),
    ]
