# Generated by Django 4.2.13 on 2024-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0004_riskassessredflag_riskassessredflagnfvariant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskassessredflag",
            name="title",
            field=models.CharField(
                help_text="Title of the risk assessment red flag", max_length=255
            ),
        ),
    ]
