# Generated by Django 4.2.14 on 2024-08-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taxonomies",
            "0006_taxonomynode_is_gender_taxonomynode_is_part_nature_and_more",
        ),
        ("composition", "0005_alter_parameter_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="qualifier",
            field=models.ForeignKey(
                blank=True,
                db_column="id_qualifier",
                help_text="(QUALIFIER vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "QUALIFIER"),
                    (
                        "extended_name__in",
                        [
                            "Equal to",
                            "Less than",
                            "Less than or equal",
                            "Greater than",
                            "Greater than or equal",
                            "Circa",
                            "traces",
                        ],
                    ),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qualifier_compositions",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="composition",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="id_unit",
                help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "UNIT"),
                    models.Q(("short_name", "root"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_compositions",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="vocab_id",
            field=models.ForeignKey(
                blank=True,
                db_column="id_param",
                help_text="(PARAM vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "PARAM"),
                    models.Q(("short_name", "root"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vocab_id_parameters",
                to="taxonomies.taxonomynode",
                verbose_name="Parameter Vocabulary Identification",
            ),
        ),
        migrations.AlterField(
            model_name="productionnovelfoodvariant",
            name="process",
            field=models.ForeignKey(
                blank=True,
                db_column="id_process",
                help_text="(MTX vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "MTX"),
                    models.Q(("short_name", "root"), _negated=True),
                    ("is_process", True),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="process_production_novel_food_variants",
                to="taxonomies.taxonomynode",
                verbose_name="Process Step",
            ),
        ),
    ]
