# Generated by Django 4.2.13 on 2024-06-25 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0005_alter_riskassessredflag_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novelfoodvariant",
            name="risk_assess_red_flag",
        ),
    ]
