# Generated by Django 4.2.14 on 2024-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "composition",
            "0006_alter_composition_qualifier_alter_composition_unit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="footnote",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
    ]
