# Generated by Django 4.2.13 on 2024-06-25 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0006_remove_novelfoodvariant_risk_assess_red_flag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionnovelfoodvariant",
            options={
                "verbose_name": "Production Process",
                "verbose_name_plural": "Production Processes",
            },
        ),
    ]
