# Generated by Django 4.2.14 on 2024-09-01 15:46

import django.db.models.deletion
from django.db import migrations, models
from django.db.utils import IntegrityError


def check_null_values(apps, schema_editor):
    ProductionNovelFoodVariant = apps.get_model(
        "composition", "ProductionNovelFoodVariant"
    )
    if ProductionNovelFoodVariant.objects.filter(process__isnull=True).exists():
        raise IntegrityError(
            "NULL values found in 'ProductionNovelFoodVariant.process' field, therefore migration "
            "cannot proceed."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0007_alter_taxonomynode_short_name"),
        ("composition", "0007_alter_composition_footnote"),
    ]

    operations = [
        migrations.RunPython(check_null_values, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="productionnovelfoodvariant",
            name="process",
            field=models.ForeignKey(
                db_column="id_process",
                help_text="(MTX vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "MTX"),
                    models.Q(("short_name", "root"), _negated=True),
                    ("is_process", True),
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_production_novel_food_variants",
                to="taxonomies.taxonomynode",
                verbose_name="Process Step",
            ),
        ),
    ]
