# Generated by Django 4.2.13 on 2024-06-25 21:05

import composition.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0007_alter_productionnovelfoodvariant_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="title",
            field=models.CharField(
                help_text="Parameter",
                max_length=255,
                unique=True,
                validators=[
                    composition.models.validate_case_insensitive_parameter_title
                ],
            ),
        ),
    ]
