# Generated by Django 4.2.14 on 2024-09-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0008_alter_productionnovelfoodvariant_process"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="composition",
            options={},
        ),
        migrations.AlterModelOptions(
            name="riskassessredflagnfvariant",
            options={},
        ),
        migrations.AlterField(
            model_name="riskassessredflagnfvariant",
            name="risk_assess_red_flag",
            field=models.ForeignKey(
                db_column="id_risk_assess_red_flag",
                on_delete=django.db.models.deletion.CASCADE,
                to="composition.riskassessredflag",
                verbose_name="Risk Assessment Red Flag",
            ),
        ),
    ]
