# Generated by Django 4.2.14 on 2024-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composition", "0009_alter_composition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposeduse",
            name="use_type",
            field=models.CharField(
                choices=[
                    ("whole foods", "Whole foods"),
                    ("food ingredients", "Food ingredients"),
                    ("food supplements", "Food supplements"),
                    (
                        "infant follow on formula",
                        "Infant formula and follow-on formula",
                    ),
                    ("special medical purpose", "Food for special medical purposes"),
                    (
                        "total diet replacement",
                        "Total diet replacement for weight control",
                    ),
                    (
                        "meal replacement for weight control",
                        "Meal replacement for weight control",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
