# Generated by Django 4.2.14 on 2024-11-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0009_alter_population_qualifier_alter_population_unit"),
        (
            "composition",
            "0012_alter_composition_qualifier_alter_composition_unit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="qualifier",
            field=models.ForeignKey(
                blank=True,
                db_column="id_qualifier",
                help_text="(QUALIFIER vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "QUALIFIER"),
                    (
                        "extended_name__in",
                        [
                            "Equal to",
                            "Less than",
                            "Less than or equal",
                            "Greater than",
                            "Greater than or equal",
                            "Circa",
                            "traces",
                        ],
                    ),
                    models.Q(("status", "D"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="qualifier_compositions",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="composition",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="id_unit",
                help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "UNIT"),
                    models.Q(("short_name", "root"), _negated=True),
                    models.Q(("status", "D"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unit_compositions",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="vocab_id",
            field=models.ForeignKey(
                blank=True,
                db_column="id_param",
                help_text="(PARAM vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "PARAM"),
                    models.Q(("short_name", "root"), _negated=True),
                    models.Q(("status", "D"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vocab_id_parameters",
                to="taxonomies.taxonomynode",
                verbose_name="Parameter Vocabulary Identification",
            ),
        ),
        migrations.AlterField(
            model_name="productionnovelfoodvariant",
            name="process",
            field=models.ForeignKey(
                db_column="id_process",
                help_text="(MTX vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "MTX"),
                    models.Q(("short_name", "root"), _negated=True),
                    ("is_process", True),
                    models.Q(("status", "D"), _negated=True),
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_production_novel_food_variants",
                to="taxonomies.taxonomynode",
                verbose_name="Process Step",
            ),
        ),
    ]
