# Generated by Django 4.2.13 on 2024-06-03 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0003_remove_question_dossier_question_applicant_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("assigned_not_started", "assigned not started"),
                            ("working_on", "working on"),
                            ("currently_working_on", "currently working on"),
                            ("has_blocker", "has blocker"),
                            ("finished", "finished"),
                        ],
                        help_text="Status of the contribution",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "id_op",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.opinion",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
