# Generated by Django 4.2.13 on 2024-07-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administrative",
            "0004_alter_mandate_question_alter_opinionpanel_opinion_and_more",
        ),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="opinion",
            field=models.ForeignKey(
                db_column="id_op",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="administrative.opinion",
            ),
        ),
    ]
