# Generated by Django 4.2.13 on 2024-07-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxonomies", "0003_alter_population_upper_range_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreqUsedVocabNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[("org_part", "Organism Part")], max_length=255
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="code_listings",
                        to="taxonomies.taxonomynode",
                        verbose_name="taxnomy node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frequently Used Vocab Node",
                "verbose_name_plural": "👩\u200d🔬 Frequently Used Vocab Nodes",
            },
        ),
    ]
