# Generated by Django 4.2.13 on 2024-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novelfoodorganism",
            name="variant",
            field=models.CharField(
                blank=True,
                help_text="STRAIN for microorganisms / VARIETY for plants / SUBSPECIES for animals",
                max_length=255,
                null=True,
            ),
        ),
    ]
