# Generated by Django 4.2.13 on 2024-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="definition",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
