# Generated by Django 4.2.13 on 2024-06-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0001_initial"),
        ("novel_food", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novelfood",
            name="nutritional_disadvantage",
        ),
        migrations.AddField(
            model_name="novelfood",
            name="has_nutri_disadvantage",
            field=models.ForeignKey(
                blank=True,
                db_column="id_has_nutri_disadvantage",
                help_text="(YESNO vocab)",
                limit_choices_to={"taxonomy__code": "YESNO"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="has_nutri_disadvantage_novel_foods",
                to="taxonomies.taxonomynode",
                verbose_name="has Nutritional Disadvantage",
            ),
        ),
        migrations.AddField(
            model_name="novelfood",
            name="nutri_disadvantage_explanation",
            field=models.TextField(
                blank=True,
                help_text="explanation in case the Novel Food has a nutritional disadvantage",
                null=True,
                verbose_name="if Nutritional Disadvantage Explain Why",
            ),
        ),
        migrations.AlterField(
            model_name="novelfood",
            name="outcome_remarks",
            field=models.TextField(
                blank=True,
                help_text="explanation in case the FinalOutcome is 'Negative' or "
                "'Partially Negative'",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="NutritionalDisadvantage",
        ),
    ]
