# Generated by Django 4.2.13 on 2024-06-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0001_initial"),
        (
            "novel_food",
            "0002_remove_novelfoodorganism_is_cell_culture_modified_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="substanceofconcernnovelfood",
            name="substance_of_concern",
            field=models.ForeignKey(
                blank=True,
                db_column="id_sub_of_concern",
                help_text="Fill only if there is a substance of concern, if not "
                "leave blank. (PARAM vocab)",
                limit_choices_to={"taxonomy__code": "PARAM"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substance_of_concern_substance_of_concern_novel_foods",
                to="taxonomies.taxonomynode",
            ),
        ),
    ]
