# Generated by Django 4.2.13 on 2024-07-03 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0002_alter_novelfood_shelflife_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={
                "verbose_name": "Family (custom taxonomy)",
                "verbose_name_plural": "📂 Families (custom taxonomy)",
            },
        ),
        migrations.AlterModelOptions(
            name="genus",
            options={
                "verbose_name": "Genus (custom taxonomy)",
                "verbose_name_plural": "📂 Genera (custom taxonomy)",
            },
        ),
        migrations.AlterModelOptions(
            name="orgtype",
            options={
                "verbose_name": "Organism Type (custom taxonomy)",
                "verbose_name_plural": "📂 Organism Types (custom taxonomy)",
            },
        ),
        migrations.AlterModelOptions(
            name="species",
            options={
                "verbose_name": "Species (custom taxonomy)",
                "verbose_name_plural": "📂 Species (custom taxonomy)",
            },
        ),
    ]
