# Generated by Django 4.2.13 on 2024-06-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0002_remove_novelfood_nutritional_disadvantage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="novelfood",
            name="final_toxicology_remarks",
            field=models.TextField(
                blank=True,
                help_text="Final toxicology assessment for all the toxicology studies",
                null=True,
            ),
        ),
    ]
