# Generated by Django 4.2.13 on 2024-06-12 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0002_orgmodification_remove_novelfoodorganism_is_gmo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chemicaltype",
            options={
                "verbose_name": "Chemical type (future use)",
                "verbose_name_plural": "📂 Chemical types (future use)",
            },
        ),
        migrations.AlterModelOptions(
            name="structurereported",
            options={
                "verbose_name": "Structure reported (future use)",
                "verbose_name_plural": "📂 Structures reported (future use)",
            },
        ),
    ]
