# Generated by Django 4.2.13 on 2024-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0003_novelfood_final_toxicology_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novelfood",
            name="outcome_remarks",
            field=models.TextField(
                blank=True,
                help_text="explanation in case the Outcome is 'Negative' or 'Partially Negative'",
                null=True,
            ),
        ),
    ]
