# Generated by Django 4.2.13 on 2024-07-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0003_alter_family_options_alter_genus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novelfood",
            name="shelflife_value",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
    ]
