# Generated by Django 4.2.13 on 2024-06-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0004_rename_id_chemical_type_chemicaltype_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemical",
            name="chemical_type",
            field=models.ForeignKey(
                blank=True,
                db_column="component_type",
                help_text="The majority of the chemical types are extracted from the "
                "OECD picklist(OECD 2012). More on the purpose of this field: 2013:EN-458 page:20",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="novel_food.chemicaltype",
            ),
        ),
    ]
