# Generated by Django 4.2.13 on 2024-07-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0005_alter_population_subgroup_and_more"),
        ("novel_food", "0005_alter_allergenicitynovelfood_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novelfoodorganism",
            name="cells_modified",
            field=models.ForeignKey(
                blank=True,
                db_column="id_cells_modified",
                help_text="(YESNO vocab)",
                limit_choices_to={"taxonomy__code": "YESNO"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cells_modified_novel_foods",
                to="taxonomies.taxonomynode",
                verbose_name="Cells Modified? (Cell Culture)",
            ),
        ),
    ]
