# Generated by Django 4.2.13 on 2024-07-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0005_alter_population_subgroup_and_more"),
        ("novel_food", "0007_alter_allergenicitynovelfood_novel_food_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificToxicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "novel_food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_toxicities",
                        to="novel_food.novelfood",
                    ),
                ),
                (
                    "specific_toxicity",
                    models.ForeignKey(
                        db_column="id_toxicity",
                        help_text="if novel food has specific toxicity, specify which one. "
                        "(TOXICITY vocab)",
                        limit_choices_to={"taxonomy__code": "TOXICITY"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novel_foods",
                        to="taxonomies.taxonomynode",
                        verbose_name="Specific Toxicity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specific Toxicity",
                "verbose_name_plural": "Specific Toxicities",
                "db_table": "SPECIFIC_TOXICITY",
            },
        ),
        migrations.AddConstraint(
            model_name="specifictoxicity",
            constraint=models.UniqueConstraint(
                fields=("novel_food", "specific_toxicity"),
                name="unique_specific_toxicity_novel_food",
            ),
        ),
    ]
