# Generated by Django 4.2.13 on 2024-07-25 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0008_specifictoxicity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novelfood",
            name="specific_toxicity",
        ),
    ]
