# Generated by Django 4.2.14 on 2024-09-01 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0007_alter_taxonomynode_short_name"),
        ("novel_food", "0012_alter_organism_vocab_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organism",
            name="vocab_id",
            field=models.ForeignKey(
                db_column="id_organism",
                help_text="(MTX vocab) - only records with '(as animal)' or '(as plant)' or "
                "'(as organism)' in the name are allowed",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "MTX"),
                    models.Q(
                        ("extended_name__icontains", "(as animal)"),
                        ("extended_name__icontains", "(as organism)"),
                        ("extended_name__icontains", "(as plant)"),
                        ("short_name__icontains", "(as animal)"),
                        ("short_name__icontains", "(as organism)"),
                        ("short_name__icontains", "(as plant)"),
                        _connector="OR",
                    ),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vocab_id_organisms",
                to="taxonomies.taxonomynode",
                verbose_name="Organism vocabulary identification",
            ),
        ),
    ]
