# Generated by Django 4.2.14 on 2024-09-02 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0013_alter_organism_vocab_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chemical",
            name="chemical_type",
        ),
        migrations.RemoveField(
            model_name="chemical",
            name="structure_reported",
        ),
        migrations.DeleteModel(
            name="ChemicalType",
        ),
        migrations.DeleteModel(
            name="StructureReported",
        ),
    ]
