# Generated by Django 4.2.14 on 2024-09-02 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0014_remove_chemical_chemical_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="substanceofconcernnovelfood",
            options={"verbose_name": "Hazard", "verbose_name_plural": "Hazards"},
        ),
    ]
