# Generated by Django 4.2.14 on 2024-09-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0007_alter_taxonomynode_short_name"),
        ("novel_food", "0016_alter_specifictoxicity_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backgroundexposureassessment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="foodcategorynovelfood",
            options={"verbose_name": "Food Category of Novel Food"},
        ),
        migrations.AlterModelOptions(
            name="hbgv",
            options={},
        ),
        migrations.AlterModelOptions(
            name="novelfoodcategorynovelfood",
            options={},
        ),
        migrations.AlterModelOptions(
            name="novelfoodchemical",
            options={},
        ),
        migrations.AlterModelOptions(
            name="novelfoodorganism",
            options={},
        ),
        migrations.AlterModelOptions(
            name="novelfoodsyn",
            options={},
        ),
        migrations.AlterModelOptions(
            name="specifictoxicity",
            options={},
        ),
        migrations.AlterModelOptions(
            name="substanceofconcernnovelfood",
            options={},
        ),
        migrations.AlterField(
            model_name="allergenicitynovelfood",
            name="allergenicity",
            field=models.ForeignKey(
                db_column="id_allergenicity",
                on_delete=django.db.models.deletion.CASCADE,
                to="novel_food.allergenicity",
                verbose_name="Allergenicity Risk",
            ),
        ),
        migrations.AlterField(
            model_name="backgroundexposureassessment",
            name="comp_of_interest",
            field=models.ForeignKey(
                blank=True,
                db_column="id_comp_of_interest",
                help_text="Compound of interest (PARAM vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "PARAM"),
                    models.Q(("short_name", "root"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comp_of_interest_bg_expo_assessments",
                to="taxonomies.taxonomynode",
                verbose_name="Compound Assessed For Background Exposure",
            ),
        ),
        migrations.AlterField(
            model_name="foodcategorynovelfood",
            name="food_category",
            field=models.ForeignKey(
                db_column="id_food_category",
                on_delete=django.db.models.deletion.CASCADE,
                to="novel_food.foodcategory",
                verbose_name="Food Category Tool",
            ),
        ),
        migrations.AlterField(
            model_name="hbgv",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_column="id_type",
                help_text="(ENDPOINT_HGV vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "ENDPOINT_HGV"),
                    models.Q(("short_name", "root"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="type_hbgvs",
                to="taxonomies.taxonomynode",
                verbose_name="Health-Based Guidance Value",
            ),
        ),
        migrations.AlterField(
            model_name="novelfoodcategorynovelfood",
            name="novel_food_category",
            field=models.ForeignKey(
                db_column="id_sub_type",
                on_delete=django.db.models.deletion.CASCADE,
                to="novel_food.novelfoodcategory",
                verbose_name="Regulation Category",
            ),
        ),
        migrations.AlterField(
            model_name="novelfoodchemical",
            name="chemical",
            field=models.ForeignKey(
                db_column="id_com",
                on_delete=django.db.models.deletion.CASCADE,
                to="novel_food.chemical",
                verbose_name="Chemical Identity",
            ),
        ),
        migrations.AlterField(
            model_name="novelfoodorganism",
            name="organism",
            field=models.ForeignKey(
                db_column="id_organism",
                on_delete=django.db.models.deletion.CASCADE,
                to="novel_food.organism",
                verbose_name="Organism Identity",
            ),
        ),
        migrations.AlterField(
            model_name="novelfoodsyn",
            name="title",
            field=models.CharField(
                db_column="study_syn",
                max_length=255,
                verbose_name="Novel/Traditional Food Synonym",
            ),
        ),
    ]
