# Generated by Django 4.2.14 on 2024-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novel_food", "0017_alter_backgroundexposureassessment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemdescriptor",
            name="value",
            field=models.CharField(
                help_text="contains e.g. the molecular formula itself if "
                "type is 'Molecular Formula', etc.",
                max_length=500,
                verbose_name="Descriptor",
            ),
        ),
    ]
