# Generated by Django 4.2.14 on 2024-12-22 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "novel_food",
            "0020_alter_backgroundexposureassessment_comp_of_interest_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodcategory",
            name="definition",
        ),
        migrations.RemoveField(
            model_name="synonymtype",
            name="definition",
        ),
    ]
