# Generated by Django 4.2.13 on 2024-06-27 09:28

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuidelineQualifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id_quideline_qualifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Guideline Qualifier",
                "verbose_name_plural": "📂 Guideline Qualifiers",
                "db_table": "GUIDELINE_QUALIFIER",
            },
        ),
        migrations.CreateModel(
            name="Subgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id_subgroup", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="subgroup", max_length=255)),
            ],
            options={
                "verbose_name": "Subgroup",
                "verbose_name_plural": "📂 Subgroups",
                "db_table": "SUBGROUP",
            },
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "📂 Taxonomies",
            },
        ),
        migrations.CreateModel(
            name="TaxonomyNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen_during_synchronization", models.BooleanField(default=False)),
                (
                    "user_synchronization_status",
                    models.CharField(
                        choices=[
                            ("A", "Imported automatically"),
                            ("a", "Added manually"),
                            ("r", "Removed manually"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="SPECIES if organism",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("scope", models.TextField(blank=True, null=True)),
                ("extended_name", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=1)),
                ("reportable", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Approved"),
                            ("D", "Deprecated"),
                            ("P", "Preliminary"),
                            ("E", "Exported"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "is_botanic",
                    models.BooleanField(
                        default=False,
                        help_text="Is this node marked as being in 'botanic' hierarchy?",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="taxonomies.taxonomynode",
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomies.taxonomy",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "📂 Taxonomy Nodes",
            },
        ),
        migrations.CreateModel(
            name="Population",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id_age", primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="Age Value"),
                ),
                (
                    "upper_range_value",
                    models.FloatField(
                        blank=True,
                        help_text="only if there is upper range value for age",
                        null=True,
                        verbose_name="Age Upper Value",
                    ),
                ),
                (
                    "qualifier",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_qualifier",
                        limit_choices_to={"taxonomy__code": "QUALIFIER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qualifier_populations",
                        to="taxonomies.taxonomynode",
                        verbose_name="Age Qualifier",
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_subgroup",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subgroup_populations",
                        to="taxonomies.subgroup",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_unit",
                        help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                        limit_choices_to={"taxonomy__code": "UNIT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit_populations",
                        to="taxonomies.taxonomynode",
                        verbose_name="Age Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Population",
                "verbose_name_plural": "📂 Populations",
                "db_table": "AGE",
            },
        ),
        migrations.CreateModel(
            name="ImplicitAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=45000)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implicit_attributes",
                        to="taxonomies.taxonomynode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedTaxonomyNodeInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=3)),
                ("index", models.IntegerField()),
                ("value", models.CharField(max_length=25500)),
                (
                    "taxonomy_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extended_info",
                        to="taxonomies.taxonomynode",
                    ),
                ),
            ],
        ),
    ]
