# Generated by Django 4.2.13 on 2024-06-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidelinequalifier",
            name="title",
            field=models.CharField(
                db_column="guideline_qualifier", max_length=255, unique=True
            ),
        ),
    ]
