# Generated by Django 4.2.13 on 2024-06-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="population",
            name="qualifier",
            field=models.ForeignKey(
                blank=True,
                db_column="id_qualifier",
                limit_choices_to={"taxonomy__code": "QUALIFIER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qualifier_populations",
                to="taxonomies.taxonomynode",
                verbose_name="Age Qualifier",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="id_unit",
                help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                limit_choices_to={"taxonomy__code": "UNIT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_populations",
                to="taxonomies.taxonomynode",
                verbose_name="Age Unit",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="upper_range_value",
            field=models.FloatField(
                blank=True,
                help_text="only if there is upper range value for age",
                null=True,
                verbose_name="Age Upper Value",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="value",
            field=models.FloatField(blank=True, null=True, verbose_name="Age Value"),
        ),
    ]
