# Generated by Django 4.2.13 on 2024-06-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0002_alter_guidelinequalifier_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="population",
            name="upper_range_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="only if there is upper range value for age",
                max_digits=10,
                null=True,
                verbose_name="Age Upper Value",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Age Value",
            ),
        ),
    ]
