# Generated by Django 4.2.13 on 2024-07-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0003_alter_population_upper_range_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="population",
            name="upper_range_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="only if there is upper range value for age",
                max_digits=10,
                null=True,
                verbose_name="Age Upper Value",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=10,
                null=True,
                verbose_name="Age Value",
            ),
        ),
        migrations.AlterField(
            model_name="taxonomynode",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="if creating new record use: NORA",
                max_length=100,
            ),
        ),
    ]
