# Generated by Django 4.2.14 on 2024-08-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0005_alter_population_subgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomynode",
            name="is_gender",
            field=models.BooleanField(
                default=False,
                help_text="Is this node marked as being in 'gender' hierarchy?",
            ),
        ),
        migrations.AddField(
            model_name="taxonomynode",
            name="is_part_nature",
            field=models.BooleanField(
                default=False,
                help_text="Does this node belong to 'PartNature' facet from MTX?",
            ),
        ),
        migrations.AddField(
            model_name="taxonomynode",
            name="is_process",
            field=models.BooleanField(
                default=False,
                help_text="Does this node belong to 'process' facet from MTX?",
            ),
        ),
        migrations.AddField(
            model_name="taxonomynode",
            name="is_yesno",
            field=models.BooleanField(
                default=False,
                help_text="Is this node marked as being in 'yesno' hierarchy?",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="qualifier",
            field=models.ForeignKey(
                blank=True,
                db_column="id_qualifier",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "QUALIFIER"),
                    models.Q(("short_name", "root"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qualifier_populations",
                to="taxonomies.taxonomynode",
                verbose_name="Age Qualifier",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="id_unit",
                help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "UNIT"),
                    ("extended_name__in", ["Hour", "Day", "Week", "Month", "Year"]),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_populations",
                to="taxonomies.taxonomynode",
                verbose_name="Age Unit",
            ),
        ),
    ]
