# Generated by Django 4.2.14 on 2024-11-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taxonomies",
            "0008_alter_population_qualifier_alter_population_subgroup_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="population",
            name="qualifier",
            field=models.ForeignKey(
                blank=True,
                db_column="id_qualifier",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "QUALIFIER"),
                    models.Q(("short_name", "root"), _negated=True),
                    models.Q(("status", "D"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="qualifier_populations",
                to="taxonomies.taxonomynode",
                verbose_name="Age Qualifier",
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="id_unit",
                help_text="use full name (e.g. 'gram' not 'g'). (UNIT vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "UNIT"),
                    ("extended_name__in", ["Hour", "Day", "Week", "Month", "Year"]),
                    models.Q(("status", "D"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unit_populations",
                to="taxonomies.taxonomynode",
                verbose_name="Age Unit",
            ),
        ),
    ]
