# Generated by Django 4.2.11 on 2024-05-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                ("id_applicant", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the applicant", max_length=255, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "APPLICANT",
            },
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                ("id_dossier", models.AutoField(primary_key=True, serialize=False)),
                (
                    "number",
                    models.CharField(
                        help_text="Dossier number", max_length=255, unique=True
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_applicant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers",
                        to="administrative.applicant",
                    ),
                ),
            ],
            options={
                "db_table": "DOSSIER",
            },
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                ("id_mandate", models.AutoField(primary_key=True, serialize=False)),
                (
                    "number",
                    models.CharField(
                        help_text="Mandate number", max_length=255, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "MANDATE",
            },
        ),
        migrations.CreateModel(
            name="Opinion",
            fields=[
                ("id_op", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the opinion", max_length=255, unique=True
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="URL to the opinion", null=True
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("efsa nda", "EFSA NDA"),
                            ("efsa praper", "EFSA PRAPeR"),
                            ("efsa cef", "EFSA CEF"),
                            ("efsa ans", "EFSA ANS"),
                            ("efsa feedap", "EFSA FEEDAP"),
                            ("efsa contam", "EFSA CONTAM"),
                        ],
                        help_text="Owner of the opinion",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, help_text="Date of publication", null=True
                    ),
                ),
                (
                    "adoption_date",
                    models.DateField(
                        blank=True, help_text="Date of adoption", null=True
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("partially_negative", "Partially Negative"),
                        ],
                        help_text="Outcome of the opinion",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "OPINION",
            },
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                ("id_panel", models.AutoField(primary_key=True, serialize=False)),
                (
                    "panel",
                    models.CharField(
                        help_text="Title of the panel", max_length=255, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "PANEL",
            },
        ),
        migrations.CreateModel(
            name="ScientificOfficer",
            fields=[
                ("id_sci_officer", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "SCI_OFFICER",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id_question", models.AutoField(primary_key=True, serialize=False)),
                (
                    "question",
                    models.CharField(
                        help_text="Question number", max_length=255, unique=True
                    ),
                ),
                (
                    "dossier",
                    models.OneToOneField(
                        blank=True,
                        db_column="id_dossier",
                        help_text="Dossier number",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="administrative.dossier",
                    ),
                ),
                (
                    "mandate",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_mandate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="administrative.mandate",
                    ),
                ),
            ],
            options={
                "db_table": "QUESTION",
            },
        ),
        migrations.CreateModel(
            name="OPScientificOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_op",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.opinion",
                    ),
                ),
                (
                    "id_sci_officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.scientificofficer",
                    ),
                ),
            ],
            options={
                "db_table": "OP_SCI_OFFICER",
            },
        ),
        migrations.CreateModel(
            name="OPQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_op",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.opinion",
                    ),
                ),
                (
                    "id_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.question",
                    ),
                ),
            ],
            options={
                "db_table": "OP_QUESTION",
            },
        ),
        migrations.CreateModel(
            name="OPAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_op",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.opinion",
                    ),
                ),
                (
                    "id_panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.panel",
                    ),
                ),
            ],
            options={
                "db_table": "OP_AUTHOR",
            },
        ),
        migrations.CreateModel(
            name="MandateType",
            fields=[
                (
                    "id_mandate_type",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the mandate type",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "helper_regulation",
                    models.CharField(
                        blank=True,
                        help_text="this field will be removed after the extraction is complete",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "mandate_type_parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_mandate_type_parent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mandate_types",
                        to="administrative.mandatetype",
                    ),
                ),
            ],
            options={
                "db_table": "MANDATE_TYPE",
            },
        ),
        migrations.AddField(
            model_name="mandate",
            name="mandate_type",
            field=models.ForeignKey(
                blank=True,
                db_column="id_mandate_type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mandates",
                to="administrative.mandatetype",
            ),
        ),
    ]
