# Generated by Django 4.2.13 on 2024-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinion",
            name="title",
            field=models.CharField(
                help_text="Title of the opinion", max_length=2000, unique=True
            ),
        ),
    ]
