# Generated by Django 4.2.13 on 2024-06-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0001_initial"),
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinion",
            name="id_op_type",
            field=models.ForeignKey(
                blank=True,
                help_text="(REF_TYPE vocab)",
                limit_choices_to={"taxonomy__code": "REF_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opinions",
                to="taxonomies.taxonomynode",
                verbose_name="Document type",
            ),
        ),
        migrations.AlterField(
            model_name="questionmandate",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                db_column="id_regulation",
                help_text="(LEGREF vocab)",
                limit_choices_to={"taxonomy__code": "LEGREF"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="regulation_questionmandates",
                to="taxonomies.taxonomynode",
            ),
        ),
    ]
