# Generated by Django 4.2.13 on 2024-06-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
