# Generated by Django 4.2.13 on 2024-06-27 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinionpanel",
            name="id",
            field=models.AutoField(
                db_column="id_op_panel", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="opinionquestion",
            name="id",
            field=models.AutoField(
                db_column="id_op_question", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="opinionsciofficer",
            name="id",
            field=models.AutoField(
                db_column="id_op_sci_officer", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="questionapplicant",
            name="applicant",
            field=models.ForeignKey(
                db_column="id_applicant",
                on_delete=django.db.models.deletion.CASCADE,
                to="administrative.applicant",
            ),
        ),
        migrations.AlterField(
            model_name="questionapplicant",
            name="id",
            field=models.AutoField(
                db_column="id_question_applicant", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="questionapplicant",
            name="question",
            field=models.ForeignKey(
                db_column="id_question",
                on_delete=django.db.models.deletion.CASCADE,
                to="administrative.question",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinionpanel",
            constraint=models.UniqueConstraint(
                fields=("opinion", "panel"), name="unique_opinion_panel"
            ),
        ),
        migrations.AddConstraint(
            model_name="opinionquestion",
            constraint=models.UniqueConstraint(
                fields=("opinion", "question"), name="unique_opinion_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="opinionsciofficer",
            constraint=models.UniqueConstraint(
                fields=("opinion", "sci_officer"), name="unique_opinion_sci_officer"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionapplicant",
            constraint=models.UniqueConstraint(
                fields=("applicant", "question"), name="unique_question_applicant"
            ),
        ),
    ]
