# Generated by Django 4.2.11 on 2024-05-14 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0002_alter_mandatetype_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="number",
        ),
        migrations.RemoveField(
            model_name="mandate",
            name="mandate_type",
        ),
        migrations.RemoveField(
            model_name="mandate",
            name="number",
        ),
        migrations.RemoveField(
            model_name="opinion",
            name="owner",
        ),
        migrations.AddField(
            model_name="mandate",
            name="helper_regulation",
            field=models.CharField(
                blank=True,
                help_text="this field will be removed after the extraction is complete",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mandate",
            name="mandate_parent",
            field=models.ForeignKey(
                blank=True,
                db_column="id_mandate_parent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mandates",
                to="administrative.mandate",
            ),
        ),
        migrations.AddField(
            model_name="mandate",
            name="title",
            field=models.CharField(
                choices=[
                    ("novel_food", "Novel food"),
                    ("new_dossier", "New dossier"),
                    ("extension_of_use", "Extension of use"),
                    ("nutrient_source", "Nutrient source"),
                    ("traditional_food", "Traditional food"),
                    ("nutrient_source", "Nutrient source"),
                ],
                default="placeholder",
                help_text="Title of the mandate type",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicant",
            name="title",
            field=models.CharField(
                help_text="Name of the applicant", max_length=255, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="MandateType",
        ),
    ]
