# Generated by Django 4.2.13 on 2024-06-03 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0002_opinion_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="dossier",
        ),
        migrations.AddField(
            model_name="question",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                db_column="id_applicant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applicant_questions",
                to="administrative.applicant",
            ),
        ),
        migrations.DeleteModel(
            name="Dossier",
        ),
    ]
