# Generated by Django 4.2.13 on 2024-07-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0003_alter_opinionpanel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandate",
            name="question",
            field=models.ForeignKey(
                db_column="id_question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandates",
                to="administrative.question",
            ),
        ),
        migrations.AlterField(
            model_name="opinionpanel",
            name="opinion",
            field=models.ForeignKey(
                db_column="id_op",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panels",
                to="administrative.opinion",
            ),
        ),
        migrations.AlterField(
            model_name="opinionquestion",
            name="opinion",
            field=models.ForeignKey(
                db_column="id_op",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="administrative.opinion",
            ),
        ),
        migrations.AlterField(
            model_name="opinionsciofficer",
            name="opinion",
            field=models.ForeignKey(
                db_column="id_op",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sci_officers",
                to="administrative.opinion",
            ),
        ),
        migrations.AlterField(
            model_name="questionapplicant",
            name="question",
            field=models.ForeignKey(
                db_column="id_question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicants",
                to="administrative.question",
            ),
        ),
    ]
