# Generated by Django 4.2.14 on 2024-08-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taxonomies",
            "0006_taxonomynode_is_gender_taxonomynode_is_part_nature_and_more",
        ),
        ("administrative", "0005_remove_opinion_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandate",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                db_column="id_regulation",
                help_text="(LEGREF vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "LEGREF"),
                    models.Q(("short_name", "root"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="regulation_mandates",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="opinion",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                db_column="id_op_type",
                help_text="(REF_TYPE vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "REF_TYPE"),
                    models.Q(("short_name", "root"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opinions",
                to="taxonomies.taxonomynode",
                verbose_name="Document type",
            ),
        ),
    ]
