# Generated by Django 4.2.14 on 2024-09-04 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0006_alter_mandate_regulation_alter_opinion_document_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question", "verbose_name_plural": "📂 Questions"},
        ),
    ]
