# Generated by Django 4.2.14 on 2024-11-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomies", "0009_alter_population_qualifier_alter_population_unit"),
        (
            "administrative",
            "0008_alter_mandate_mandate_type_alter_mandate_regulation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandate",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                db_column="id_regulation",
                help_text="(LEGREF vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "LEGREF"),
                    models.Q(("short_name", "root"), _negated=True),
                    models.Q(("status", "D"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regulation_mandates",
                to="taxonomies.taxonomynode",
            ),
        ),
        migrations.AlterField(
            model_name="opinion",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                db_column="id_op_type",
                help_text="(REF_TYPE vocab)",
                limit_choices_to=models.Q(
                    ("taxonomy__code", "REF_TYPE"),
                    models.Q(("short_name", "root"), _negated=True),
                    models.Q(("status", "D"), _negated=True),
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opinions",
                to="taxonomies.taxonomynode",
                verbose_name="Document type",
            ),
        ),
    ]
