# Generated by Django 4.2.14 on 2024-11-21 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0009_alter_mandate_regulation_alter_opinion_document_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mandatetype",
            options={
                "verbose_name": "Mandate Type",
                "verbose_name_plural": "📂 Mandate Types",
            },
        ),
    ]
