# Generated by Django 4.2.14 on 2024-12-22 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrative", "0010_alter_mandatetype_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mandatetype",
            name="definition",
        ),
    ]
